export default {
    quesAndAns :[
        {id:0,ques:'How can I trust the people you have on the app?', ans : 'All professionals available for home deep cleaning service on the app are verified by Urban Company. They are professionals with significant experience in the field and have detailed profiles that are visible on the app and our website.'},
        {id:1,ques:'I have a duplex. Can you clean it?', ans : 'We clean anything from a studio apartment to a villa. The options on the app give you the provision to book any type of home deep cleaning service. If you do not find your option on the app, get in touch with the professional by selecting a service closest to what you want and communicate the same to the professional, to find out the right cost. In case you face any issue, give our customer service center a call.'},
        {id:2,ques:'I have never had cleaning done before. Will it cost extra?', ans : "There are no extra charges or hidden costs involved. What you see on the app, is what you get. When you book the service, there are details given in the app of what you can get for the money you pay. It doesn't matter if your house has never been cleaned or has been cleaned regularly."},
        {id:3,ques:"Do you also provide cleaning services for office space?", ans : "Yes, we do. You can log on to the Urban Company app and search for office deep cleaning in the services section to check the availability of the service in your location."},
        {id:4,ques:"What do I need before home deep cleaning service?", ans : "We request you to remove all the expensive and valuable items from the cabinets and the wardrobes before the internal cleaning begins. Anything kept outside or in a showcase or a trolley also needs to be removed. Apart from this, we recommend you have a detailed discussion with the assigned professional so you can communicate your expectations from the service."},
        {id:5,ques:"Are your products pet friendly?", ans : "The products used by our professional deep cleaners are of the highest grade in the market and are safe for pets as well."},
        {id:6,ques:"What is the Urban Company's promise?", ans : "Urban Company’s promise with home deep cleaning service (and every other offering we have) is to give you: highly trained professionals who hold the highest standards of quality, high quality of products- cleaning agents that are professional grade & customer protection against any damages."},
        {id:7,ques:"What can home deep cleaning do that my maid can't?", ans:"Home deep cleaning includes everything that a standard cleaning by a house maid will not. For starters, the equipment and the number of people involved in the process are more. A manual cleaning would usually just involve sweeping the floor, dusting and perhaps cleaning the ceiling fans grudgingly. Home deep cleaning  includes cleaning every nook and corner of your house in the best way possible."},
        {id:8,ques:"Do I need to be home when the cleaning process is on?", ans:"Ideally, it would be better if you are home to ensure that the job is done to your liking. If there are particular areas in your house where you need more attention, you can always communicate that to the cleaning professional."},
        {id:9,ques:"What does home deep cleaning not include?", ans:"If you book the home deep cleaning service from Urban Company, here is what is not included in the service: cleaning of utensils, walls and ceiling, floor polishing, wet shampooing of blinds, chair, sofa and carpets & polishing of wooden furniture."},
        {id:10,ques:"I only want my balcony cleaned. What should I do?", ans:"We give you the provision to pick the service in its entirety by booking a full deep cleaning service or just select services that cover certain parts of your house. Apart from the many options available, you can simply go for the balconies and window cleaning package."},
        {id:11,ques:"Do you also offer furniture cleaning?", ans:"Yes, we do. If you do not wish to go for the home deep cleaning service, you can choose any specific service or a package in furniture cleaning."},
        {id:12,ques:"What if I am not satisfied with the service?", ans:"At Urban Company, we hold the highest standards of quality, which is why, becoming a partner on Urban Company is a long process that has multiple levels of quality checks. We also hold the customer reviews in the highest regard and urge you to leave a pleasant or an unpleasant review based on your experience. If you face any issue with the service, our customer care service center would be happy to help you with the same."},
        {id:13,ques:"How much time will it take to get my house deep cleaned?", ans:"It depends on the service, the package you choose and the size of your house (number of bedrooms). At the time of booking, we give you a fair idea of the duration of the service in the ''view details'' section. On an average, home deep cleaning takes about 6 hours."}
    ]
}